{{- if eq (default "Deployment" .Values.kind) "CronJob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "workload.fullname" . }}
  namespace: {{ include "workload.namespace" $ }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJobSchedule | quote }}
  concurrencyPolicy: {{ .Values.cronJobConcurrencyPolicy }}
  {{- if not (kindIs "invalid" .Values.cronJobStartingDeadlineSeconds) }}
  startingDeadlineSeconds: {{ .Values.cronJobStartingDeadlineSeconds }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.cronJobSuccessfulJobsHistoryLimit) }}
  successfulJobsHistoryLimit: {{ .Values.cronJobSuccessfulJobsHistoryLimit }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.cronJobFailedJobsHistoryLimit) }}
  failedJobsHistoryLimit: {{ .Values.cronJobFailedJobsHistoryLimit }}
  {{- end }}
  jobTemplate:
    spec:
      {{- if and (not (kindIs "invalid" .Values.job.ttlSecondsAfterFinished)) (ne (toString .Values.job.ttlSecondsAfterFinished) "") }}
      ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
      {{- end }}
      backoffLimit: {{ .Values.job.backoffLimit }}
      {{- if not (kindIs "invalid" .Values.job.activeDeadlineSeconds) }}
      activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
      {{- end }}
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "workload.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: {{ default "Never" .Values.restartPolicy }}
          {{- if kindIs "bool" .Values.automountServiceAccountToken }}
          automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
          {{- end }}
          {{- with .Values.runtimeClassName }}
          runtimeClassName: {{ . }}
          {{- end }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
          serviceAccountName: {{ include "workload.serviceAccountName" . }}
          {{- end }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.initContainers }}
          initContainers:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ default .Chart.Name .Values.containerName }}
              {{- with .Values.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- with .Values.command }}
              command:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- include "workload.environment" . | trim | nindent 14 }}
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.topologySpreadConstraints }}
          topologySpreadConstraints:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
