{{- range .Values.persistentVolumeClaims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ include "workload.namespace" $ }}
  labels:
    {{- include "workload.labels" $ | nindent 4 }}
spec:
  {{- with .storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .storage }}
{{- end }}