{{- $kind := default "Deployment" .Values.kind -}}
{{- if and .Values.service.enabled (has $kind (list "Deployment" "DaemonSet" "StatefulSet" "ScaledObject")) (gt (int .Values.replicaCount) 0) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workload.fullname" . }}
  namespace: {{ include "workload.namespace" $ }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
    {{- range .Values.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .containerPort }}
      protocol: {{ default "TCP" .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "workload.selectorLabels" $ | nindent 4 }}
{{- end }}