replicaCount: 1
automountServiceAccountToken: false
containerName: app
commonLabels:
  app.kubernetes.io/component: web
image:
  repository: busybox
  pullPolicy: IfNotPresent
command:
  - sh
  - -c
args:
  - sleep 3600
networkPolicies:
  - name: allow-ingress
    spec:
      podSelector:
        matchLabels:
          app.kubernetes.io/name: workload
      policyTypes:
        - Ingress
      ingress:
        - from:
            - namespaceSelector: {}
