name: ci

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    permissions:
      contents: read
    uses: f2calv/gha-workflows/.github/workflows/lint.yml@v1

  release:
    name: release (${{ matrix.chart }})
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        chart:
          - workload
          - signalcli
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/_publish-chart.yml
    with:
      chart: ${{ matrix.chart }}
    secrets: inherit
